### ISSUE TITLE
dub run fails without internet connection.

### ISSUE THREAD

**Issue by SuperDoxin** [D-Programming-Language/dub#746] opened 2016-01-09 01:23 UTC
dub build doesn't work when you don't have an internet connection. I'm not sure if it actually fails or is waiting for a timeout, but it's a bug either way.

**Comment by MrSmith33** [comment] 2016-01-09 20:17
try using `--nodeps` flag

**Comment by SuperDoxin** [comment] 2016-01-10 15:54
while it's possible to work around the issue, that's all it is, a workaround. not a fix. I shouldn't need to manually tell dub to not use an internet connection when none is available.

**Comment by s-ludwig** [comment] 2016-01-10 16:58
I think we can close this as a duplicate of #559.

**Closed by s-ludwig** 2016-01-10 16:58 UTC
