### ISSUE TITLE
Static lib as extension .a with LDC and MSVC toolchain

### ISSUE THREAD

**Issue by redstar** [D-Programming-Language/dub#687] opened 2015-09-18 06:30 UTC
As LDC for Win64 with MSVC toolchain is maturing I noticed the following: a static library is named with the Unix conventions: a `lib` prefix and a `.a` extension.
This is the right thing if the target is MinGW32 but not for the MSVC toolchain. Here I expect the same as for DMD: no `lib` prefix and a `.lib` extension.
I admit that I have no clue how dub can distinguish between ldc targeting MinGW and ldc targeting MSVC toolchain.

**Comment by s-ludwig** [comment] 2015-09-18 06:53
Duplicate of #618. Interestingly, I've already started to implement a fix, but forgot about the branch: https://github.com/D-Programming-Language/dub/commits/fix_issue_618
I'll finish that for 0.9.25.

**Closed by s-ludwig** 2015-09-18 06:53 UTC
