### ISSUE TITLE
Usability improvement: what if `dub upgrade` was calling `dub clean-caches`?

### ISSUE THREAD

**Issue by p0nce** [D-Programming-Language/dub#650] opened 2015-08-12 10:01 UTC
The rationale is that when I use `dub upgrade` I want the latest version of everything, not the latest version of things based on what the DUB cache know.

**Comment by s-ludwig** [comment] 2015-08-12 10:24
Closing as duplicate of https://github.com/D-Programming-Language/dub/issues/528 (the semantics proposed there are basically equivalent).

**Closed** 2015-08-12 10:47 UTC
