### ISSUE TITLE
dub build causes weird message:

### ISSUE THREAD

**Issue by denizzzka** [D-Programming-Language/dub#568] opened 2015-05-07 23:05 UTC
Error executing command build:
no package file was found, expected one of the following: [immutable(FilenameAndFormat)("dub.json", json), immutable(FilenameAndFormat)("package.json", json)]

**Comment by denizzzka** [comment] 2015-05-07 23:06
DUB version 0.9.23

**Comment by MartinNowak** [comment] 2015-05-08 00:42
Duplicate of #564.

**Closed by MartinNowak** 2015-05-08 00:42 UTC
