### ISSUE TITLE
Cached packages are never removed due to build output files

### ISSUE THREAD

**Issue by luismarques** [D-Programming-Language/dub#481] opened 2014-12-27 18:20 UTC
When I add a package, build a project, and then try to remove the package this happens:

```
$ dub remove vibe-d
Removing vibe-d in /Users/luismarques/.dub/packages/vibe-d-0.7.21/
Failed to remove vibe-d 0.7.21: Untracked file found, aborting package removal, file: /Users/luismarques/.dub/packages/vibe-d-0.7.21/libvibe-d.a
Please remove the package folder manually or use --force-remove.
Continuing with other packages (if any).
```

Is this expected? If it's just the normal result of building a package then I don't see why that should impede package removal...

Happens in OS X at least. (10.10)

**Comment by MartinNowak** [comment] 2015-01-02 18:43
duplicate of #377

**Closed by MartinNowak** 2015-01-02 18:43 UTC
